services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_HOST=user-service-db
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=root
      - MONGO_DB=users
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .env:/app/.env
    networks:
      - calentar
    depends_on:
      - user-service-db  

  user-service-db:
    image: mongo:latest
    container_name: user-service-db
    ports:
      - "27018:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users
    networks:
      - calentar
    volumes:
      - mongo_data:/data/db 

networks:
  calentar:
    driver: bridge

volumes:
  mongo_data:
