services:
  entry-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entry-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_HOST=entry-service-db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=Calentar
      - DATABASE_PORT=5432
    volumes:
      - .env:/app/.env 
    networks:
      - calentar
    depends_on:
      - entry-service-db

  entry-service-db:
    container_name: entry-service-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Calentar
    networks:
      - calentar
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  calentar:
    driver: bridge

volumes:
  postgres_data: 
